---

- name: manage basic config
  hosts: routers
  gather_facts: false
  
  tasks:
    - name: set hostname and no http server configuration
      cisco.ios.ios_config:
        save_when: modified
        lines:
          - hostname "{{inventory_hostname}}"
          - no ip http server
      register: output

    - name: Add Banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          This banner was created by JoeSchmoh using Ansible
        state: present

    - name: Print out the output to standard out
      debug:
        var: output.stdout_lines

    - name: save running config
      cisco.ios.ios_config:
        save_when: modified
  
